# Generated by Django 4.1.4 on 2022-12-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationdetail',
            name='title',
        ),
    ]
