# Generated by Django 4.1.4 on 2022-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_remove_presentationdetail_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ('num',)},
        ),
        migrations.AddField(
            model_name='presentationdetail',
            name='title',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
    ]
